### PR TITLE
update pre-commit, go and format files

### PR DESCRIPTION
**Pull request by esacteksab**
General housekeeping like our other repos. Updates pre-commit, updates go packages and as a result of pre-commit changes, formats files to follow our conventions.

### CODE REVIEW

**Review by rpdelaney — APPROVED** [review]
Looks like the required checks are wonky and may have to be fixed in legendary-waddle @esacteksab

**Comment by esacteksab** [comment]
> Looks like the required checks are wonky and may have to be fixed in legendary-waddle @esacteksab

Yeah, this one stumped me. There is no config in the repo. It's not defined as a required check (it's not blocking merges). I don't know how it exists.

**Comment by rpdelaney** [comment]
Maybe we should try importing it into terraform? It would be amusing if the github provider gives us a user interface for fixing this that the web console didn't. And we need to have all repos in terraform anyway

**Comment by esacteksab** [comment]
> Maybe we should try importing it into terraform? It would be amusing if the github provider gives us a user interface for fixing this that the web console didn't. And we need to have all repos in terraform anyway

This isn't already in TF? Then, let's! Please!

**Comment by rpdelaney** [comment]
Oh I must have misunderstood this:

> There is no config in the repo.

I thought you meant it's not in `/trussworks-prod/github-prod` in legendary waddle.

**Comment by esacteksab** [comment]
> Oh I must have misunderstood this:
> 
> > There is no config in the repo.
> 
> I thought you meant it's not in `/trussworks-prod/github-prod` in legendary waddle.

I meant there isn't a circle-ci config, so I'm not sure what's defining this check. I thought you meant there may be something defined in the TF for this check, or that importing this repo might include the check that doesn't show up in the UI and allow us to get rid of it.

**Comment by rpdelaney** [comment]
We don't know why this `CircleCI Pipeline` check is required. It's not in the terraform for the github provider, it's not there in the web console settings on the repo, and it's not there on other PRs (like #64). So I'm going to just merge this and move on with the mystery unsolved.

**Pull request merged**
